version: '3.1'

services:

  client:
    build: ./client
    command: npm run start-dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      # - /app/node_modules
  
  server:
    build: ./server
    command: npm run start-dev
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      # - /app/node_modules
    depends_on:
      - db
    networks:
      - pgnetwork
  
  db:
    image: postgres
    ports:
      - "5433:5432"
    networks:
      - pgnetwork

  pgadmin:
    links:
      - db
    image: fenglc/pgadmin4
    volumes:
      - /data/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    networks:
      - pgnetwork
    restart: unless-stopped

networks:
  pgnetwork:
    driver: bridge
