exports.seed = async (knex) => {
  await knex('entities').del();
  await knex.raw('ALTER SEQUENCE entities_id_seq RESTART WITH 1');
  return knex('entities').insert([
    {
      name: 'Florestinha',
      description: 'Produtor',
      entity_type_id: 2,
      address: 'Vale Verde',
      address_complement: '',
      city: 'Alto Paraíso de Goiás',
      region: 'Goiás',
      country_code: 'BR',
      post_code: '73770-000',
      latitude: '-14.197362',
      longitude: '-47.590000',
    },
    {
      name: 'Terra Booma',
      description: 'Produtor',
      entity_type_id: 2,
      address: 'Moinho',
      address_complement: '',
      city: 'Alto Paraíso de Goiás',
      region: 'Goiás',
      country_code: 'BR',
      post_code: '73770-000',
      latitude: '-14.079782',
      longitude: '-47.481171',
    },
    {
      name: 'CEPEAS',
      description: 'Centro de Pesquisa em Agricultura Sintrópica',
      entity_type_id: 3,
      address: 'Rodovia GO-239, km 8',
      address_complement: '',
      city: 'Alto Paraíso de Goiás',
      region: 'Goiás',
      country_code: 'BR',
      post_code: '73770-000',
      latitude: '-14.151594',
      longitude: '-47.570748',
    },
    {
      name: 'Feira Do Produtor Rural',
      description: 'Feira ao Sábados e Terças-feirais',
      entity_type_id: 4,
      address: 'Rua Joaquim Costa',
      address_complement: '',
      city: 'Alto Paraíso de Goiás',
      region: 'Goiás',
      country_code: 'BR',
      post_code: '73770-000',
      latitude: '-14.136004',
      longitude: '-47.514361',
    },
    {
      name: 'Feira Do CAT',
      description: 'Feira Aos Domingos e Quintas-feiras',
      entity_type_id: 4,
      address: 'Av. Ary Valadão Filho, 1310',
      address_complement: '',
      city: 'Alto Paraíso de Goiás',
      region: 'Goiás',
      country_code: 'BR',
      post_code: '73770-000',
      latitude: '-14.133450',
      longitude: '-47.518572',
    },
    {
      name: 'Dax',
      description: 'Proprietário da FLorestinha',
      entity_type_id: 5,
      address: 'Vale Verde',
      address_complement: '',
      city: 'Alto Paraíso de Goiás',
      region: 'Goiás',
      country_code: 'BR',
      post_code: '73770-000',
      latitude: '-14.137483',
      longitude: '-47.5255588',
    },
  ]);
};
