export default {
  Spacing: {
    Main: {
      position: 'absolute',
      left: '0%',
      right: '0%',
      top: '0%',
      bottom: '0%',
      background: '#FFFFFF',
    },
    Picture: {
      position: 'absolute',
      width: '40px',
      height: '40px',
      left: '16px',
      top: '9px',
      borderRadius: '5px',
    },
    Title: {
      position: 'absolute',
      width: '289px',
      height: '20px',
      left: '66px',
      top: '9px',
    },
    DateTime: {
      position: 'absolute',
      width: '121px',
      height: '15px',
      left: '66px',
      top: '29px',
    },
    Text: {
      position: 'absolute',
      width: '342px',
      height: '66px',
      left: '16px',
      top: '59px',
    },
  },
  Fonts: {
    TitleBold: {
      fontFamily: 'Open Sans',
      fontStyle: 'normal',
      fontWeight: 600,
      lineHeight: 'normal',
      fontSize: '14px',
      letterSpacing: '0.01em',
      color: '#000000',
    },
    Title: {
      fontFamily: 'Open Sans',
      fontStyle: 'normal',
      fontWeight: 'normal',
      lineHeight: 'normal',
      fontSize: '14px',
      letterSpacing: '0.01em',
      color: '#000000',
    },
    Text: {
      fontFamily: 'Open Sans',
      fontStyle: 'normal',
      fontHeight: 'normal',
      lineHeight: 'normal',
      fontSize: '11px',
      letterSpacing: '0.01em',
    },
  },
};
